# Generated by Django 3.2 on 2021-08-07 09:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CoordinatorInCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.BinaryField(null=True)),
                ('name', models.BinaryField()),
                ('dob', models.BinaryField()),
                ('gender', models.BinaryField()),
                ('mobile_no', models.BinaryField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('pincode', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.city')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ParentsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.BinaryField(null=True)),
                ('consent', models.BooleanField(default=True)),
                ('name', models.BinaryField()),
                ('dob', models.BinaryField()),
                ('mobile_no', models.BinaryField(null=True)),
                ('gender', models.BinaryField()),
                ('address', models.BinaryField()),
                ('pincode', models.BinaryField()),
                ('no_of_family_members', models.BinaryField()),
                ('children_count', models.BinaryField()),
                ('first_password', models.CharField(default='helloworld14', max_length=20)),
                ('password_changed', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.city')),
                ('edu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.education')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.occupation')),
            ],
        ),
        migrations.CreateModel(
            name='ReligiousBelief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(null=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.coordinatorincharge')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherInCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.BinaryField(null=True)),
                ('name', models.BinaryField()),
                ('dob', models.BinaryField()),
                ('gender', models.BinaryField()),
                ('mobile_no', models.BinaryField(null=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.coordinatorincharge')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.session')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacherincharge')),
            ],
        ),
        migrations.CreateModel(
            name='SuperCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.BinaryField()),
                ('name', models.BinaryField()),
                ('dob', models.BinaryField()),
                ('gender', models.BinaryField()),
                ('mobile_no', models.BinaryField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.BinaryField()),
                ('name', models.BinaryField()),
                ('email', models.BinaryField(null=True)),
                ('dob', models.BinaryField()),
                ('mobile_no', models.BinaryField(null=True)),
                ('gender', models.BinaryField()),
                ('consent', models.BooleanField(default=True)),
                ('adult', models.BinaryField()),
                ('pincode', models.BinaryField()),
                ('address', models.BinaryField()),
                ('first_password', models.CharField(default='helloworld14', max_length=20)),
                ('password_changed', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.city')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.parentsinfo')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.session')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.state')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.teacherincharge')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='parentsinfo',
            name='religion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.religiousbelief'),
        ),
        migrations.AddField(
            model_name='parentsinfo',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.state'),
        ),
        migrations.AddField(
            model_name='parentsinfo',
            name='type_of_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.familytype'),
        ),
        migrations.AddField(
            model_name='parentsinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.state'),
        ),
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organizationtypes'),
        ),
        migrations.CreateModel(
            name='ModuleOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre', models.BooleanField(null=True)),
                ('draft', models.BooleanField()),
                ('nutriGarden', models.CharField(max_length=10, null=True)),
                ('source_fruits_vegetables', models.CharField(max_length=255, null=True)),
                ('grow_own_food', models.CharField(max_length=255, null=True)),
                ('if_grow_what', models.CharField(default='NA', max_length=255, null=True)),
                ('reason_gardening', models.CharField(max_length=255, null=True)),
                ('healthy_diet', models.CharField(max_length=255, null=True)),
                ('imp_nutrients', models.CharField(max_length=255, null=True)),
                ('citrus_fruits_blank', models.CharField(max_length=255, null=True)),
                ('not_richsource_iron', models.CharField(max_length=255, null=True)),
                ('source_vitaminA', models.CharField(max_length=255, null=True)),
                ('imp_eat_fruits_vegetables', models.CharField(max_length=255, null=True)),
                ('reason_wide_variety_food', models.CharField(max_length=255, null=True)),
                ('microgreen', models.CharField(max_length=255, null=True)),
                ('microgreen_example', models.CharField(max_length=255, null=True)),
                ('harvestdays_microgreen', models.CharField(max_length=255, null=True)),
                ('microgreen_grow_seeds_kitchen', models.CharField(max_length=255, null=True)),
                ('microgreen_nutritiousthan_fullgrownvegetables', models.CharField(max_length=255, null=True)),
                ('microgreen_immunity', models.CharField(max_length=255, null=True)),
                ('microgreen_variety', models.CharField(max_length=255, null=True)),
                ('microgreen_source', models.CharField(max_length=255, null=True)),
                ('newspaper_grow_microgreen', models.CharField(max_length=255, null=True)),
                ('microgreen_first_step', models.CharField(max_length=255, null=True)),
                ('soaking_time_seeds', models.CharField(max_length=255, null=True)),
                ('microgreen_watering', models.CharField(max_length=255, null=True)),
                ('microgreen_use', models.CharField(max_length=255, null=True)),
                ('submission_timestamp', models.DateTimeField(null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentsinfo')),
            ],
        ),
        migrations.CreateModel(
            name='FormDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.BooleanField()),
                ('pre', models.BooleanField()),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField(null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.form')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.session')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacherincharge')),
            ],
        ),
        migrations.AddField(
            model_name='coordinatorincharge',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='coordinatorincharge',
            name='super_coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.supercoordinator'),
        ),
        migrations.AddField(
            model_name='coordinatorincharge',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.state'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre', models.BooleanField(null=True)),
                ('draft', models.BooleanField()),
                ('weight', models.FloatField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('height', models.FloatField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(214)])),
                ('waist', models.FloatField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('hip', models.FloatField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('submission_timestamp', models.DateTimeField(null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentsinfo')),
            ],
        ),
    ]
