# Generated by Django 3.2 on 2021-08-05 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210804_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsinfo',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.session'),
        ),
    ]
