# Generated by Django 3.2 on 2021-11-04 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211104_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsinfo',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.parentsinfo'),
        ),
    ]
