# Generated by Django 3.2 on 2021-08-10 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210807_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsinfo',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.parentsinfo'),
        ),
    ]
