# Generated by Django 3.2 on 2021-07-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='pre',
            field=models.BooleanField(default=True),
        ),
    ]
