# Generated by Django 3.2 on 2021-08-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_studentsinfo_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_date',
            field=models.DateField(),
        ),
    ]
