# Generated by Django 3.2 on 2021-07-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_studentsinfo_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsinfo',
            name='name',
            field=models.BinaryField(max_length=500),
        ),
    ]
