# Generated by Django 3.2 on 2021-07-22 10:37

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_activity_pre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='pre',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='studentsinfo',
            name='dob',
            field=models.DateField(error_messages={'invalid': 'Date of Birth is out of range'}, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2016, 7, 23)), django.core.validators.MinValueValidator(limit_value=datetime.date(2006, 7, 26))]),
        ),
    ]
