# Generated by Django 3.2 on 2021-11-04 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211104_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physique',
            name='pre',
        ),
    ]
