# Generated by Django 3.2 on 2021-07-23 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_studentsinfo_dob'),
        ('accounts', '0005_auto_20210722_1607'),
    ]

    operations = [
    ]
