# Generated by Django 3.2 on 2021-08-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210816_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinatorincharge',
            name='first_password',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AddField(
            model_name='coordinatorincharge',
            name='password_changed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacherincharge',
            name='first_password',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AddField(
            model_name='teacherincharge',
            name='password_changed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parentsinfo',
            name='first_password',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='parentsinfo',
            name='password_changed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studentsinfo',
            name='first_password',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='studentsinfo',
            name='password_changed',
            field=models.BooleanField(default=True),
        ),
    ]
