# Generated by Django 3.2 on 2021-07-23 12:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20210723_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='hip',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='waist',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentsinfo',
            name='dob',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2016, 7, 24)), django.core.validators.MinValueValidator(limit_value=datetime.date(2006, 7, 27))]),
        ),
    ]
