# Generated by Django 3.2 on 2021-08-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_session_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
