# Generated by Django 3.2 on 2021-07-23 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20210723_1513'),
        ('accounts', '0008_auto_20210723_1807'),
    ]

    operations = [
    ]
