# Generated by Django 3.2 on 2021-08-21 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_student_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_session',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.teacherincharge'),
            preserve_default=False,
        ),
    ]
