# Generated by Django 3.2 on 2021-07-23 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_coordinatorincharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherincharge',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.coordinatorincharge'),
        ),
        migrations.AddField(
            model_name='teacherincharge',
            name='createdAt',
            field=models.DateTimeField(null=True),
        ),
    ]
