# Generated by Django 3.2 on 2021-10-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_student_session_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentsinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
