# Generated by Django 3.2 on 2021-07-23 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210723_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherincharge',
            name='coordinator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.coordinatorincharge'),
            preserve_default=False,
        ),
    ]
