# Generated by Django 3.2 on 2021-10-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_parentsinfo_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentsinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, default='undraw_profile_1.svg', null=True, upload_to=''),
        ),
    ]
