# Generated by Django 3.2 on 2021-07-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210724_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='height',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='hip',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='waist',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='weight',
            field=models.FloatField(default=None, null=True),
        ),
    ]
