# Generated by Django 3.2 on 2021-07-23 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_teacherincharge_coordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherincharge',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.coordinatorincharge'),
        ),
    ]
