# Generated by Django 3.2 on 2021-10-18 14:16

from django.db import migrations, models
import django.db.models.deletion
from shared.encryption import EncryptionHelper

encryptionHelper = EncryptionHelper()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_parentsinfo_profile_pic"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coordinatorincharge",
            old_name="name",
            new_name="fname",
        ),
        migrations.RenameField(
            model_name="parentsinfo",
            old_name="name",
            new_name="fname",
        ),
        migrations.RenameField(
            model_name="studentsinfo",
            old_name="name",
            new_name="fname",
        ),
        migrations.RenameField(
            model_name="supercoordinator",
            old_name="name",
            new_name="fname",
        ),
        migrations.RenameField(
            model_name="teacherincharge",
            old_name="name",
            new_name="fname",
        ),
        migrations.RemoveField(
            model_name="parentsinfo",
            name="address",
        ),
        migrations.RemoveField(
            model_name="studentsinfo",
            name="address",
        ),
        migrations.AddField(
            model_name="coordinatorincharge",
            name="aadhar",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="coordinatorincharge",
            name="lname",
            field=models.BinaryField(default=encryptionHelper.encrypt(" ")),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coordinatorincharge",
            name="mname",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="parentsinfo",
            name="aadhar",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="parentsinfo",
            name="lname",
            field=models.BinaryField(default=encryptionHelper.encrypt(" ")),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parentsinfo",
            name="mname",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="studentsinfo",
            name="aadhar",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="studentsinfo",
            name="lname",
            field=models.BinaryField(default=encryptionHelper.encrypt(" ")),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentsinfo",
            name="mname",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="supercoordinator",
            name="aadhar",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="supercoordinator",
            name="lname",
            field=models.BinaryField(default=encryptionHelper.encrypt(" ")),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supercoordinator",
            name="mname",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="teacherincharge",
            name="aadhar",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="teacherincharge",
            name="lname",
            field=models.BinaryField(default=encryptionHelper.encrypt(" ")),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacherincharge",
            name="mname",
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name="parentsinfo",
            name="children_count",
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name="parentsinfo",
            name="edu",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.education",
            ),
        ),
        migrations.AlterField(
            model_name="parentsinfo",
            name="no_of_family_members",
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name="parentsinfo",
            name="occupation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.occupation",
            ),
        ),
        migrations.AlterField(
            model_name="parentsinfo",
            name="religion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.religiousbelief",
            ),
        ),
        migrations.AlterField(
            model_name="parentsinfo",
            name="type_of_family",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.familytype",
            ),
        ),
    ]
