# Generated by Django 3.2 on 2021-07-24 10:59

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210723_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsinfo',
            name='dob',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2016, 7, 25)), django.core.validators.MinValueValidator(limit_value=datetime.date(2006, 7, 28))]),
        ),
    ]
