# Generated by Django 3.2 on 2021-07-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_studentsinfo_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatorincharge',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='teacherincharge',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
