# Generated by Django 3.2 on 2021-10-19 16:16

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_supercoordinator_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supercoordinator',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.rename),
        ),
    ]
