# Generated by Django 3.2 on 2021-07-24 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210724_1728'),
        ('accounts', '0016_auto_20210724_1642'),
    ]

    operations = [
    ]
