# Generated by Django 3.2 on 2021-07-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_merge_0014_auto_20210724_1728_0016_auto_20210724_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentsinfo',
            name='email',
            field=models.BinaryField(max_length=500),
        ),
    ]
