# Generated by Django 3.2 on 2021-10-20 08:02

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_supercoordinator_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentsinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.rename),
        ),
        migrations.AlterField(
            model_name='studentsinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.rename),
        ),
    ]
