# Generated by Django 3.2 on 2021-10-20 08:20

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20211020_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinatorincharge',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.rename),
        ),
    ]
