# Generated by Django 3.2 on 2021-07-25 04:43

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_parentsinfo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentsinfo',
            name='pincode',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='studentsinfo',
            name='dob',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2016, 7, 26)), django.core.validators.MinValueValidator(limit_value=datetime.date(2006, 7, 29))]),
        ),
    ]
