# Generated by Django 3.2 on 2021-07-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210725_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinatorincharge',
            name='createdAt',
        ),
    ]
