# Generated by Django 3.2 on 2021-10-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_coordinatorincharge_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supercoordinator',
            name='email',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='supercoordinator',
            name='mobile_no',
            field=models.BinaryField(null=True),
        ),
    ]
