# Generated by Django 3.2 on 2021-07-25 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_activity_height'),
        ('accounts', '0020_remove_coordinatorincharge_createdat'),
    ]

    operations = [
    ]
