# Generated by Django 3.2 on 2021-10-21 15:48

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20211020_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherincharge',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.rename),
        ),
    ]
