# Generated by Django 3.2 on 2021-10-23 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_teacherincharge_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentsinfo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='parentsinfo',
            name='state',
        ),
    ]
