# Generated by Django 3.2 on 2021-10-24 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20211023_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_income', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RationCardColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ration_card_color', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='studentsinfo',
            old_name='rollno',
            new_name='unique_no',
        ),
        migrations.RemoveField(
            model_name='parentsinfo',
            name='children_count',
        ),
        migrations.RemoveField(
            model_name='parentsinfo',
            name='edu',
        ),
        migrations.RemoveField(
            model_name='parentsinfo',
            name='no_of_family_members',
        ),
        migrations.RemoveField(
            model_name='parentsinfo',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='parentsinfo',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='parentsinfo',
            name='type_of_family',
        ),
        migrations.CreateModel(
            name='SecondaryReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_family_members', models.IntegerField(null=True)),
                ('edu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.education')),
                ('family_income', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.familyincome')),
                ('occupation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.occupation')),
                ('ration_card_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.rationcardcolor')),
                ('religion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.religiousbelief')),
                ('type_of_family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.familytype')),
            ],
        ),
        migrations.AddField(
            model_name='studentsinfo',
            name='secondary_reg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.secondaryreg'),
        ),
    ]
