# Generated by Django 3.2 on 2021-10-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20211024_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentsinfo',
            name='pincode',
        ),
        migrations.AlterField(
            model_name='organization',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
