# Generated by Django 3.2 on 2021-10-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20211024_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentsinfo',
            name='consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentsinfo',
            name='consent',
            field=models.BooleanField(default=False),
        ),
    ]
